name: Test client application

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install dependencies 
        run: cd client && npm ci

      - name: Lint Code
        run: cd client && npm run lint

      - name: Test code
        run: cd client && npm test